const Local = [
    {
        name: 'Les Paletuviers',
        type: 'local',
        region: ['African', 'European', 'Cameroonian'],
        profile: './Les Paletuviers/profile.jpeg',
        price: '5000f',
        contact: '6 98 21 12 0',
        facebook: 'https://www.facebook.com/lespaletuviersmatanda/',
        email: 'paletuviersmatanda@gmail.com',
        location: 'Bonassama, Bonaberi, Douala',
        menu: ['./Les Paletuviers/Pic 1.jpeg', './Les Paletuviers/Pic 2.jpeg', './Les Paletuviers/Pic 3.jpeg', './Les Paletuviers/Pic 5.jpeg'],
        time: ['14h-23h','11h-23h'],
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    {
        name: 'la Baleine blue de massa',
        region: ['African', 'European', 'French', 'Cocktails'],
        type: 'local',
        profile: './la baleine blue/Profile.jpg',
        price: '5000f',
        contact: ['6 94 37 14 60', '6 99 54 70 8'],
        email: 'labaleinebluedemassa@gmail.com',
        location: 'Base Navale de Douala, à 50m du Marché Poisson , Bonanjo, Douala',
        menu: ['./la baleine blue de massa/pic 1.jpeg', './la baleine blue de massa/pic 2.jpeg','./la baleine blue de massa/pic 3.jpeg','./la baleine blue de massa/pic 4.jpeg', './la baleine blue de massa de massa/pic 5.jpeg','./la baleine blue de massa/pic 6.jpeg','./la baleine blue de massa/pic 7.jpeg'],
        time: '06h-00h',
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    {
       name: 'La Pirogue',
       type: 'local',
       profile: './La Pirogue/profile.jpg',
       price: '3500f',
       contact: ['6 96 60 27 07', '2 43 59 74 63'],
       facebook: 'https://m.facebook.com/Restaurant-la-Pirogue-1628976614001675/',
       location: 'Carrefour Deido plage, Douala',
       menu: ['./La Pirogue/Pic 1.jpg', './La Pirogue/Pic 2.jpg', './La Pirogue/Pic 3.jpg', './La Pirogue/Pic 4.jpg','./La Pirogue/Pic 5.jpg', './La Pirogue/Pic 6.jpg', './La Pirogue/Pic 7.jpg', './La Pirogue/Pic 8.jpg'],
       time: ['07h-23h', '07h-00h'],
       days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
       icons: ["Icons/instagram-2-1-logo-svgrepo-com.svg", "Icons/facebook-svgrepo-com.svg", "Icons/twitter-svgrepo-com.svg", "Icons/gmail-svgrepo-com.svg"]
    },
    {
        name: 'Les Peroquets',
        type: 'local',
        region: ['African', 'European'],
        profile: './Les Peroquets/images/Profile.jpeg',
        price: '6000f',
        contact: '6 51 65 14 81',
        email: 'les2perroquets@gmail.com',
        location: 'Rue Tokoto, 165 Rue Ngosso Din, Bali , Douala',
        menu: ['./Les Peroquets/images/Pic 1.jpeg', './Les Peroquets/images/Pic 3.jpeg', './Les Peroquets/images/Pic 4.jpeg', './Les Peroquets/images/Pic 5.jpeg', './Les Peroquets/images/Pic 6.jpeg', './Les Peroquets/images/Pic 7.jpeg', './Les Peroquets/images/Pic 9.jpeg', './Les Peroquets/images/Pic 10.jpeg', './Les Peroquets/images/Pic 11.jpeg', './Les Peroquets/images/Pic 12.jpeg', './Les Peroquets/images/Pic 13.jpeg', './Les Peroquets/images/Pic 14.jpeg', './Les Peroquets/images/Pic 15.jpeg', './Les Peroquets/images/Pic 16.jpeg',],
        time: '12h-23h',
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    {
        name: 'Les Paletuviers',
        type: 'local',
        profile: './Les Paletuviers/profile.jpeg',
        price: '2000f',
        contact: '6 98 21 12 01',
        facebook: 'https://www.facebook.com/lespaletuviersmatanda/',
        email: 'paletuviersmatanda@gmail.com',
        location: 'Bonassama, Bonaberi, Douala',
        menu: ['./Les Paletuviers/Pic 1.jpeg', './Les Paletuviers/Pic 2.jpeg', './Les Paletuviers/Pic 3.jpeg', './Les Paletuviers/Pic 5.jpeg'],
        time: '11h-23h',
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    {
        name: 'la Baleine blue de massa',
        type: 'local',
        region: ['African', 'European', 'French', 'Cocktails'],
        profile: './la baleine blue de massa/Profile.jpg',
        price: '5000f',
        contact: ['6 94 37 14 60 ', '6 99 54 70 87'],
        email: 'labaleinebluedemassa@gmail.com',
        location: 'Base Navale de Douala, à 50m du Marché Poisson , Bonanjo, Douala',
        menu: ['./la baleine blue de massa/pic 1.jpeg', './la baleine blue de massa/pic 2.jpeg','./la baleine blue de massa/pic 3.jpeg','./la baleine blue de massa/pic 4.jpeg', './la baleine blue de massa/pic 5.jpeg','./la baleine blue de massa/pic 6.jpeg','./la baleine blue de massa/pic 7.jpeg'],
        time: '06h-00h',
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    {
       name: 'La Pirogue',
       type: 'local',
       profile: './La Pirogue/profile.jpg',
       price: '3500f',
       contact: ['6 96 60 27 07', '2 43 59 74 63'],
       facebook: 'https://m.facebook.com/Restaurant-la-Pirogue-1628976614001675/ ',
       location: 'Carrefour Deido plage, Douala',
       menu: ['./La Pirogue/Pic 1.jpg', './La Pirogue/Pic 2.jpg', './La Pirogue/Pic 3.jpg', './La Pirogue/Pic 4.jpg','./La Pirogue/Pic 5.jpg', './La Pirogue/Pic 6.jpg', './La Pirogue/Pic 7.jpg', './La Pirogue/Pic 8.jpg'],
       time: ['07h-23h', '07h-00h'],
       days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
       icons: ["Icons/instagram-2-1-logo-svgrepo-com.svg", "Icons/facebook-svgrepo-com.svg", "Icons/twitter-svgrepo-com.svg", "Icons/gmail-svgrepo-com.svg"]
    }
]

const Dinner = [
    {
        name:'Oasis Cave',
        type: 'diner',
        region: ['African', 'European', 'Cocktail'],
        profile:'./Oasis Cave/Profile.jpeg',
        Price: '4000f',
        contact: '6 91 28 49 85',
        location: 'Base Navale de Douala Bonanjo Douala',
        menu: ['./Oasis Cave/images/pic 1.jpeg', './Oasis Cave/images/pic 4.jpeg', './Oasis Cave/images/pic 6.jpeg'],
        time: '10h-00h',
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    {
        name: 'Clavio',
        type: 'dinner',
        region: ['Lounge', 'Bar', 'Grillades', 'Rooftop'],
        profile: './Clavio/images/Profile.jpeg',
        price: '5000f',
        contact: '6 98 26 89 14',
        facebook: 'https://facebook.com/clavioakwaofficiel',
        location: 'Base Navale de Douala Bonanjo Douala',
        menu: ['./Clavio/images/pic 1.jpeg', './Clavio/images/pic 3.jpeg','./Clavio/images/pic 4.jpeg','./Clavio/images/pic 5.jpeg'],
        time: '10h-00h',
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    {
        name: 'Saga Africa',
        type: 'dinner',
        region: ['African', 'European', 'French', 'Cocktails'],
        profile: './Saga Africa/Profile.jpeg',
        price: '5000f',
        contact: '6 51 65 14 81',
        facebook: 'https://m.facebook.com/SagaAfricaAkwa/',
        email: 'sagaafricaresa@gmail.com',
        location: 'Boulevard de la Liberté Akwa I, Akwa, Douala',
        menu: ['./Saga Africa/1.jpeg', './Saga Africa/2.jpeg', './Saga Africa/3.jpeg', './Saga Africa/4.jpeg', './Saga Africa/5.jpeg', './Saga Africa/6.jpeg', './Saga Africa/7.jpeg', './Saga Africa/8.jpeg', './Saga Africa/9.jpeg', './Saga Africa/10.jpeg', './Saga Africa/11.jpeg', './Saga Africa/12.jpeg', './Saga Africa/13.jpeg'],
        time: '11h-23h',
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    {
        name: 'Opiom',
        type: 'dinner',
        region: ['Louge', 'Grill', 'Bar'],
        profile: './Opiom/profile.jpg',
        price: '2000f',
        contact: '6 95 23 99 28',
        facebook: 'facebook.com/OPIOM-Bonamoussadi-958453004176352/',
        location: 'Boulevard de la Liberté Akwa I, Akwa, Douala',
        menu: ['./Opiom/1.jpeg', './Opiom/2.jpeg', './Opiom/3.jpeg', './Opiom/4.jpeg', './Opiom/5.jpeg', './Opiom/6.jpeg', './Opiom/7.jpeg', './Opiom/8.jpeg', './Opiom/9.jpeg', './Opiom/10.jpeg', './Opiom/11.jpeg'],
        time: '11h-23h',
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    {
        name: 'la Baleine blue de massa',
        type: 'dinner',
        region: ['Grill', 'Cameroonian'],
        profile: './la baleine blue de massa/Profile.jpg',
        price: '5000f',
        contact: ['6 94 37 14 60', ''],
        email: 'labaleinebluedemassa@gmail.com',
        location: 'Base Navale de Douala, à 50m du Marché Poisson',
        menu: ['./la baleine blue de massa/pic 1.jpeg', './la baleine blue de massa/pic 2.jpeg','./la baleine blue de massa/pic 3.jpeg','./la baleine blue de massa/pic 4.jpeg', './la baleine blue de massa/pic 5.jpeg','./la baleine blue de massa/pic 6.jpeg','./la baleine blue de massa/pic 7.jpeg'],
        time: ['14h-23h', '11h-23h'],
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
]



const BEVERAGES = [
    {
        name: 'Fun Center',
        region: ['Pizza', 'Cocktails'],
        profile: './Fun center/images/Profile.jpeg',
        price: '5000f',
        contact: '+ 237 6 56 55 56 55',
        facebook: 'www.facebook.com/funcenter237',
        location: 'Rue Tokoto, Rue des pavés, Bonapriso , Douala',
        menu:['./Fun center/images/pic 1.jpeg', './Fun center/images/pic 2.jpeg'],
        time: ['07h-23h', '09h-23h'],
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    {
        name: 'Be Bop',
        region: ['Bar', 'Cocktails'],
        profile: './Be Bop/images/Profile.JPG',
        price: '5000f',
        contact: '696734852',
        email: 'africa_bio@yahoo.fr',
        location: 'Rue Tokoto, angle Rue Entrée Casino, Bonapriso , Douala',
        menu: ['./Be Bop/images/pic 1.JPG', './Be Bop/images/pic 2.JPG', './Be Bop/images/pic 3.JPG', './Be Bop/images/pic 4.JPG', './Be Bop/images/pic 5.JPG'],
        time: '07h-00h',
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    
]

const BREAKFAST = [
    {
        name: 'Le Fouquet',
        type: 'breakfast',
        region: ['African', 'European', 'Cameroonian'],
        profile: './Le Fouquet/images/Profile.jpeg',
        price: '5000f',
        contact: '+237 6 99 77 42 95',
        region: ['African', 'European', 'Camerounian'],
        location: 'Rue Franqueville, à coté du Glacier Moderne, Akwa',
        menu: ['./Le Fouquet/images/Pic 1.jpeg', './Le Fouquet/images/Pic 2.jpeg', './Le Fouquet/images/Pic 3.jpeg', './Le Fouquet/images/Pic 4.jpeg', './Le Fouquet/images/Pic 5.jpeg', './Le Fouquet/images/Pic 6.jpeg', './Le Fouquet/images/Pic 8.jpeg', './Le Fouquet/images/Pic 9.jpeg', './Le Fouquet/images/Pic 10.jpeg'],
        time: ['12h-00h', '12h-01h'],
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    {
        name: 'Lynk Garden',
        type: 'breakfast',
        region: ['Cafe', 'Bar'],
        profile: './Lynk Garden/images/Profile.JPG',
        price: '8000f',
        contact: '696 001 832',
        email: 'lynkafrique@gmail.com',
        location: 'Bonapriso, Douala',
        menu: ['./Lynk Garden/images/Pic 1.JPG', './Lynk Garden/images/Pic 2.JPG', './Lynk Garden/images/Pic 3.JPG', './Lynk Garden/images/Pic 4.JPG', './Lynk Garden/images/Pic 5.JPG', './Lynk Garden/images/Pic 6.JPG', './Lynk Garden/images/Pic 7.JPG', './Lynk Garden/images/Pic 8.JPG', './Lynk Garden/images/Pic 9.JPG', './Lynk Garden/images/Pic 10.JPG',],
        time: '12h-20h',
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    },
    {
        name: 'Terrrific Coffee',
        type: 'breakfast',
        region: ['Lounge', 'Cafe'],
        profile: './Terrrific Coffee/images/Profile.jpeg',
        price: '1000f',
        contact: '6 79 70 10 13',
        facebook: 'https://m.facebook.com/Terrificcoffee2018/',
        email: 'support@terrificcoffeecm.com',
        location: 'Près d’hôtel Serena, Sable Bonamoussadi',
        menu: ['./Terrrific Coffee/images/Pic 1.jpeg', './Terrrific Coffee/images/Pic 2.jpeg', './Terrrific Coffee/images/Pic 3.jpeg', './Terrrific Coffee/images/Pic 5.jpeg', './Terrrific Coffee/images/Pic 6.jpeg',],
        time: ['06h-22h', '11h-22h', '06h- 23h', '08h-23h'],
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
]

const dessert = [
    
    {
        name: 'My Sweetea',
        type: 'dessert',
        region: 'Milktea shop',
        profile: './My Sweetea/images/Profile.jpg',
        price: '2000f',
        contact: '6 75 94 19 80',
        facebook: 'https://m.facebook.com/My-sweeTEA-430201030765017',
        location: 'en face Centre Spirituel Jésuite, Tradex Bonamoussadi , Douala',
        menu: ['./My Sweetea/images/Pic 2.jpg', './My Sweetea/images/Pic 2.jpg'],
        time: '10h-20h',
        days: ['Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    {
        name: 'Nice Cream',
        type: 'dessert',
        region: ['Glace', 'Crepes', 'Pizza'],
        profile: './Nice Cream/images/Profile.jpeg',
        price: '1500f',
        contact: '690 03 03 44',
        email: 'doualanicecream@gmail.com',
        location: 'Rue Boué De Lapeyrère, Akwa (en face Drugstore), Akwa, Douala',
        menu: ['./Nice Cream/images/Pic 1.jpeg', './Nice Cream/images/Pic 4.jpeg', './Nice Cream/images/Pic 8.jpeg', './Nice Cream/images/Pic 9.jpeg',],
        time: '11h-23h',
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    {
        name: 'Maison H',
        type: 'dessert',
        region: ['Glacier', 'European', 'Patisserie'],
        profile: './Maison H/images/Profile.JPG',
        price: '2500f',
        contact: '6 56 00 55 55 ',
        email: 'maisonhsarl@gmail.com',
        location: 'Rue Tokoto, 165 Rue Ngosso Din, Bali , Douala',
        menu: ['./Maison H/images/Pic 1.jpeg', './Maison H/images/Pic 2.jpeg', './Maison H/images/Pic 3.jpeg', './Maison H/images/Pic 7.jpeg', './Maison H/images/Pic 8.jpeg', './Maison H/images/Pic 10.jpeg', './Maison H/images/Pic 11.jpeg', './Maison H/images/Pic 12.jpeg', './Maison H/images/Pic 15.jpeg'],
        time: '07h-23',
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    {
        name: 'Fun Center',
        type: 'dessert',
        region: ['Pizza', 'Cocktails'],
        profile: './Fun center/images/Profile.jpeg',
        price: '5000f',
        contact: '+ 237 6 56 55 56 55',
        facebook: 'www.facebook.com/funcenter237',
        location: 'Rue Tokoto, Rue des pavés, Bonapriso , Douala',
        menu:['./Fun center/images/pic 1.jpeg', './Fun center/images/pic 2.jpeg'],
        time: ['07h-23h', '09h-23h'],
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
]

const FOREIGN = [
    {
        name: 'Opiom',
        type: 'foreign',
        region: ['Louge', 'Grill', 'Bar'],
        profile: './Opiom/profile.jpg',
        price: '2000f',
        contact: '6 95 23 99 28',
        facebook: 'facebook.com/OPIOM-Bonamoussadi-958453004176352/',
        location: 'Boulevard de la Liberté Akwa I, Akwa, Douala',
        menu: ['./Opiom/1.jpeg', './Opiom/2.jpeg', './Opiom/3.jpeg', './Opiom/4.jpeg', './Opiom/5.jpeg', './Opiom/6.jpeg', './Opiom/7.jpeg', './Opiom/8.jpeg', './Opiom/9.jpeg', './Opiom/10.jpeg', './Opiom/11.jpeg'],
        time: '11h-23h',
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    {
        name: 'Saga Africa',
        type: 'foreign',
        region: ['European', 'French', 'Cocktails'],
        profile: './Saga Africa/Profile.jpeg',
        price: '5000f',
        contact: '6 51 65 14 81',
        facebook: 'https://m.facebook.com/SagaAfricaAkwa/',
        email: 'sagaafricaresa@gmail.com',
        location: 'Boulevard de la Liberté Akwa I, Akwa, Douala',
        menu: ['./Saga Africa/1.jpeg', './Saga Africa/2.jpeg', './Saga Africa/3.jpeg', './Saga Africa/4.jpeg', './Saga Africa/5.jpeg', './Saga Africa/6.jpeg', './Saga Africa/7.jpeg', './Saga Africa/8.jpeg', './Saga Africa/9.jpeg', './Saga Africa/10.jpeg', './Saga Africa/11.jpeg', './Saga Africa/12.jpeg', './Saga Africa/13.jpeg'],
        time: '11h-23h',
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    {
       name: 'La Broche',
       type: 'foreign',
       region: 'American',
       profile: './La Broche/profile.jpeg',
       price: '8500f',
       contact: ['+237 675 444 361', '+237 697 704 427'],
       location: 'À 200m de la sortie du Supermarché Casino, près du Collège IPN, Bonapriso, Douala',
       menu: ['./La Broche/Pic 1.jpeg', './La Broche/Pic 3.jpeg', './La Broche/Pic 4.jpeg', './La Broche/Pic 5.jpeg','./La Broche/Pic 6.jpeg', './La Broche/Pic 7.jpeg', './La Broche/Pic 9.jpeg', './La Broche/Pic 10.jpeg', './La Broche/Pic 11.jpeg'],
       time: ['11h-15h', '18h-23h'],
       days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
       icons: ["Icons/instagram-2-1-logo-svgrepo-com.svg", "Icons/facebook-svgrepo-com.svg", "Icons/twitter-svgrepo-com.svg", "Icons/gmail-svgrepo-com.svg"]
    }
]

const LUNCH = [
    {
        name: 'Les Paletuviers',
        type: 'lunch',
        region: ['African', 'European', 'Cameroonian'],
        profile: './Les Paletuviers/profile.jpeg',
        price: '2000f',
        contact: '6 98 21 12 01',
        facebook: 'https://www.facebook.com/lespaletuviersmatanda/ ',
        email: 'paletuviersmatanda@gmail.com',
        location: 'Bonassama, Bonaberi, Douala',
        menu: ['./Les Paletuviers/Pic 1.jpeg', './Les Paletuviers/Pic 2.jpeg', './Les Paletuviers/Pic 3.jpeg', './Les Paletuviers/Pic 5.jpeg'],
        time: ['14h-23h', '11h-23h'],
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    {
        name: 'Saga Africa',
        type: 'lunch',
        region: ['Afriican', 'European', 'French', 'Cocktail'],
        profile: './Saga Africa/Profile.jpeg',
        price: '5000f',
        contact: '6 51 65 14 81',
        facebook: 'https://m.facebook.com/SagaAfricaAkwa/',
        email: 'sagaafricaresa@gmail.com',
        location: 'Boulevard de la Liberté Akwa I, Akwa, Douala',
        menu: ['./Saga Africa/1.jpeg', './Saga Africa/2.jpeg', './Saga Africa/3.jpeg', './Saga Africa/4.jpeg', './Saga Africa5.jpeg', './Saga Africa/6.jpeg', './Saga Africa/7.jpeg', './Saga Africa/8.jpeg', './Saga Africa/9.jpeg', './Saga Africa/10.jpeg', './Saga Africa/11.jpeg', './Saga Africa/12.jpeg', './Saga Africa/13.jpeg'],
        time: '11h-23h',
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    {
        name:'Oasis Cave',
        type: 'lunch',
        region: ['African', 'European', 'Cocktail'],
        profile:'./Oasis Cave/Profile.jpeg',
        Price: '4000f',
        contact: '6 91 28 49 85',
        location: 'Base Navale de Douala Bonanjo Douala',
        menu: ['./Oasis Cave/images/pic 1.jpeg', './Oasis Cave/images/pic 4.jpeg', './Oasis Cave/images/pic 6.jpeg'],
        time: '10h-00h',
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
]

const WINE = [
    {
        name: 'Opiom',
        region: ['Lounge', 'Grill', 'Bar'],
        profile: './Opiom/profile.jpg',
        price: '2000f',
        contact: '6 95 23 99 28',
        facebook: 'facebook.com/OPIOM-Bonamoussadi-958453004176352/',
        location: 'Boulevard de la Liberté Akwa I, Akwa, Douala',
        menu: ['./Opiom/1.jpeg', './Opiom/2.jpeg', './Opiom/3.jpeg', './Opiom/4.jpeg', './Opiom/5.jpeg', './Opiom/6.jpeg', './Opiom/7.jpeg', './Opiom/8.jpeg', './Opiom/9.jpeg', './Opiom/10.jpeg', './Opiom/11.jpeg'],
        time: '11h-23h',
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    {
        name:'Oasis Cave',
        type: 'diner',
        region: ['African', 'European', 'Cocktail'],
        profile:'./Oasis Cave/Profile.jpeg',
        Price: '4000f',
        contact: '6 91 28 49 85',
        location: 'Base Navale de Douala Bonanjo Douala',
        menu: ['./Oasis Cave/images/pic 1.jpeg', './Oasis Cave/images/pic 4.jpeg', './Oasis Cave/images/pic 6.jpeg'],
        time: '10h-00h',
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
    {
        name: 'Clavio',
        type: 'dinner',
        region: ['Lounge', 'Bar', 'Grillades', 'Rooftop'],
        profile: './Clavio/images/Profile.jpeg',
        price: '5000f',
        contact: '6 98 26 89 14',
        facebook: 'https://facebook.com/clavioakwaofficiel',
        location: 'Base Navale de Douala Bonanjo Douala',
        menu: ['./Clavio/images/pic 1.jpeg', './Clavio/images/pic 3.jpeg','./Clavio/images/pic 4.jpeg','./Clavio/images/pic 5.jpeg'],
        time: '10h-00h',
        days: ['Monday', 'Teusday', 'Wednesday', 'Thursday', 'Friday', 'Saturday','Sunday'],
    },
]
